baseURL = "/"
title = "Draw Closer - A Blog by Sharon Wu"
enableRobotsTXT = true
# this example loads the theme as hugo module
# comment out line below, and uncomment the line after it if you prefer to load the theme normally
# theme = ["github.com/onweru/compose"] # edit this if you'ld rather use a fork of this repo
theme = "compose"
enableGitInfo = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

#  menu items
[[menu.main]]
  name = "Posts"
  weight = 2
  url = "docs/"

[[menu.main]]
  name = "Tags"
  weight = 3
  url = "tags/"

[[menu.main]]
  name = "About Me"
  weight = 4
  url = "about/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      typographer = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
    style = "monokai"
    tabWidth = 2
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[taxonomies]
  category = "categories"
  tag = "tags"

# disableKinds = ["taxonomy", "taxonomyTerm"]

# Everything below this are Site Params
[params]
  repo = "https://github.com/sharonWU0505"
  uniqueHomepage = true
  mainSections = ["docs"]
  mobileNavigation = "left"
  time_format_blog = "Monday, January 02, 2006"
  time_format_default = "January 2, 2006"
  enableDarkMode = true # set to false to disable darkmode by default # user will still have the option to use dark mode

  # sets the maximum number of lines per codeblock. The codeblock will however be scrollable and expandable.
  codeMaxLines = 20

  # disable showing line numbers by default. Switch to `true` if you'd rather have them on.
  codeLineNumbers = false

  customCSS = ["/css/fix-grid-width.css", "/css/custom.css", "/css/index-posts.css", "/css/posts-list.css", "/css/post.css"]

  subSections = ["2022", "2021", "2020"]

  # Site logo
  [[params.sites]]
    name = "GitHub"
    icon = "/images/logo-github.svg"
    url = "https://github.com/sharonWU0505"

  [[params.sites]]
    name = "Medium"
    icon = "/images/logo-medium.svg"
    url = "https://medium.com/@ronronn"

  # optional
  # attribution. Feel free to delete this
  [params.author]
    name = "Sharon Wu"
    url = "https://www.linkedin.com/in/yasyuanwu/"
